const countries = {
  kolkata: "Asia/Kolkata",
  seoul: "Asia/Seoul",
  hobart: "Australia/Hobart",
  currie: "Australia/Currie",
  melbourne: "Australia/Melbourne",
  sydney: "Australia/Sydney",
  brisbane: "Australia/Brisbane",
  lindeman: "Australia/Lindeman",
  adelaide: "Australia/Adelaide",
  darwin: "Australia/Darwin",
  perth: "Australia/Perth",
  eucla: "Australia/Eucla",
  dubai: "Asia/Dubai",
  tokyo: "Asia/Tokyo",
  berlin: "Europe/Berlin",
  ponape: "Pacific/Ponape",
  hongkong: "Asia/Hong_Kong",
  manila: "Asia/Manila",
  manila: "Europe/Moscow",
  helsinki: "Europe/Helsinki",
};
module.exports = countries;
